create table CATAGORY (
    id INT PRIMARY KEY,
    NAME VARCHAR(100) UNIQUE NOT NULL,
    DESCRIPTION VARCHAR(200),
    ACTIVE_STATUS BOOLEAN
);

create table PRODUCT (
    id INT PRIMARY KEY,
    SKU_CODE VARCHAR(50) UNIQUE NOT NULL ,
    PRODUCT_NAME VARCHAR(100) NOT NULL,
    DESCRIPTION VARCHAR(200),
    PRICE DOUBLE NOT NULL,
    STOCK_QUANTITY INT NOT NULL,
    STATUS VARCHAR(10),
    CATAGORY_ID INT ,
    CONSTRAINT FK_CATAGORY FOREIGN KEY (CATAGORY_ID)
        REFERENCES CATAGORY(ID)
);

